### ISSUE TITLE
Rename InputTypes

### ISSUE THREAD

**Issue by martin-braun** [manuelcanepa/wpf-prompt-dialog#1]
Hi, simple but useful idea. Many people built something like this for themselves, but why re-invent the wheel.

Although, your InputType is not in English. "Numero" can be guessed, but for "Fecha" I had to check the source. Since the package is not used by many so far, I suggest to accept a breaking change and rename those to "Number" and "Date" before too many people would be affected by it.

**Comment by manuelcanepa** [comment]
Glad to hear that. I can take a look in a few days, buy maybe you can create a pull request. You are right, "Fecha" is "Date" and "Numero" is "Number".
