### ISSUE TITLE
Change requests

### ISSUE THREAD

**Issue by dbCF** [manuelcanepa/wpf-prompt-dialog#3]
Hi,

First of all, thank you for this dialog. Perfect for lazy people!

I did some adjustments to the `Dialog.xaml` and would appreciate if you could put them into the master branch:

```xml
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        x:Class="PromptDialog.Dialog"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        WindowStartupLocation="CenterScreen"
        SizeToContent="Height"
        Width="300"
        WindowStyle="SingleBorderWindow"
        ResizeMode="NoResize">
    <StackPanel Margin="5">
        <TextBlock Name="txtQuestion" Margin="5" TextWrapping="Wrap" />
        <TextBox Name="txtResponse" Margin="5" Visibility="Collapsed" />
        <PasswordBox Name="txtPasswordResponse" Visibility="Collapsed" />
        <DatePicker Name="dtpDateResponse" Visibility="Collapsed" />
        <StackPanel Orientation="Horizontal" Margin="5" HorizontalAlignment="Right">
            <Button Content="_Ok" IsDefault="True" Margin="5" Padding="5" Click="btnOk_Click" />
            <Button Content="_Cancel" IsCancel="True" Margin="5" Padding="5" Click="btnCancel_Click" />
        </StackPanel>
    </StackPanel>
</Window>
```

Yes, a pull request would have been an option but as I said "lazy people"...

Additionally, I'd like to have this dialog modal and not show up in the taskbar. You know, like a dialog. ;)

Best regards,
   Carsten

**Comment by martin-braun** [comment]
If you are confident, you can do a PR on GitHub like I did. If it doesn't compile and run, @manuelcanepa will report back. ;)

Just edit the file in this repo and it will automate the fork, branch, PR without much hassle. Just don't forget to explain your changes in the PR quickly.

**Comment by dbCF** [comment]
I've created a pull request and hope it will be used in the main branch.
